GET https://training-assistant-app.herokuapp.com/api/exercise/all
Accept: json

#{
#  "data": [
#    {
#      "name": "Растяжка коленями к груди",
#      "description": "Ложитесь спиной на пол, ноги вытянуты. Поднимите колено и схватите его обеими руками. Подтяните колено как можно ближе к груди, прямая разноименная нога при этом должна лежать на полу. Оставайтесь в этом положении несколько секунд",
#      "duration": 60000,
#      "experience": 5,
#      "muscleGroups": [
#        {
#          "name": "Ноги",
#          "description": "Нижние конечности, присоединённые к туловищу."
#        },
#        {
#          "name": "Туловище",
#          "description": "Часть тела между ногами и головой, исключая руки."
#        }
#      ]
#    }
#  ]
#}
###
