# Generated by Django 3.1.7 on 2021-03-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
