# Generated by Django 3.1.7 on 2021-03-05 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sber_backend', '0002_auto_20210302_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sber_backend.exercise')),
            ],
        ),
    ]
