# Generated by Django 3.1.7 on 2021-03-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_backend', '0003_trainingsession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingSession',
            new_name='ExerciseSession',
        ),
    ]
