# Generated by Django 3.1.7 on 2021-03-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sber_backend', '0004_auto_20210305_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesession',
            name='end',
        ),
    ]
