# Generated by Django 3.1.7 on 2021-03-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sber_backend', '0006_musclegroup_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
